name: ETL Pipeline

on:
  workflow_dispatch:  # Ejecucion manual con botón
  schedule:
    - cron: '0 14 * * *'  # Todos los días a las 8:00 AM CDMX (14:00 UTC)

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    # 1. Bajar código de repo
    - name: Checkout del código
      uses: actions/checkout@v4

    # 2. Instalar Python
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. Instalar librerías
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 4. Correr el ETL (Conectando los secretos)
    - name: Ejecutar ETL (Extract-Transform-Load)
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: python src/main.py
